### ISSUE TITLE
Failed to get user name

### ISSUE THREAD

**Issue by krisrajz** [Azure-Samples/active-directory-dotnet-iwa-v2#24]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@krisrajz 
Can you provide repro steps? 
Did you follow the steps in the README.md? 
What is your configuration? is your machine domain joined or AAD joined?

As it's opened we need more information to help you. As far as I'm concerned I cannot repro this.

**Comment by jennyf19** [comment]
@krisrajz any update on this?
