### ISSUE TITLE
Error while copying content to a stream

### ISSUE THREAD

**Issue by smillas** [Azure-Samples/active-directory-dotnet-iwa-v2#30]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I cloned the project to local and I edited the ClientId in appsettings file. Using user in AAD joined machine

### Any log messages given by the failure
>Error while copying content to a stream.

### OS and Version?
Windows 10

### Mention any other details that might be useful
I run the project, but i can't get my information. I have tried adding the TenantId but doesn't work.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@smillas I tried the sample and could not repo it.
Do you have specificities in your network? a proxy?

**Comment by smillas** [comment]
> @smillas I tried the sample and could not repo it.
> Do you have specificities in your network? a proxy?

Could be. We work with VPN and with remote desktops, but i had not have any issue with this. We work in Azure AD. What parameters could I check?

**Comment by jmprieur** [comment]
@smillas : I don't know
Maybe send me a call stack?

**Comment by jmprieur** [comment]
Closing as there is no answer
